name: LightSource
main: ykt.BeYkeRYkt.LightSource.LightSource
version: 1.4
description: More Lights!
author: BeYkeRYkt
commands:
   ls:
      description: Main command
   light:
      description: Main command for static lights