name: LightSource
main: ru.BeYkeRYkt.LightSource.LightSource
version: 2.2.1
description: More Lights!
author: BeYkeRYkt
softdepend: [Multiverse-Core]
depend: [LightAPI]
commands:
   ls:
      description: Main command
   light:
      description: Main command for static lights
permissions:
  ls.admin:
    default: false
  ls.lightcreator:
    default: false