name: LightSource
main: ykt.BeYkeRYkt.LightSource.LightSource
version: 2.0.1-Reload-LolliCake
description: More Lights!
author: BeYkeRYkt
commands:
   ls:
      description: Main command
   light:
      description: Main command for static lights
permissions:
  ls.admin:
    default: false