name: LightSource
main: ykt.BeYkeRYkt.LightSource.LightSource
version: 1.5
description: More Lights!
author: BeYkeRYkt
commands:
   ls:
      description: Main command
permissions:
  lightsource.admin:
    default: false